version: '3'
services:

  wordpress:
    build: .
    volumes:
      - .:/bedrock
    environment:
      WP_ENV: development
      VIRTUAL_HOST: ${SERVER_NAME}
      WP_HOME: http://${SERVER_NAME}
      WP_SITEURL: http://${SERVER_NAME}/wp
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
#      XDEBUG_CONFIG: remote_host=172.22.5.156
    depends_on:
      - mysql
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
    driver: local
